import { OrderIntent } from '@domain';
import { TradeFill } from '../engine/types';
import { DecisionTrace } from '../agents/contracts';

/**
 * Risk check result
 */
export interface RiskCheckResult {
  /** Name/identifier of the check */
  check: string;
  /** Whether the check passed */
  passed: boolean;
  /** Reason for pass/fail */
  reason: string;
}

/**
 * Risk assessment result
 */
export interface RiskAssessment {
  /** Checks that passed */
  checksPassed: RiskCheckResult[];
  /** Checks that failed */
  checksFailed: RiskCheckResult[];
  /** Whether execution should be blocked */
  blocked: boolean;
}

/**
 * Decision log entry - records when an agent makes a decision
 */
export interface DecisionLog {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp of decision */
  timestamp: string;
  /** Order intents generated by the decision */
  intents: OrderIntent[];
  /** Number of intents that were filled */
  filledCount: number;
  /** Number of intents that were rejected */
  rejectedCount: number;
  /** The full decision trace */
  trace?: DecisionTrace;
  /** Optional metadata */
  metadata?: Record<string, unknown>;
  /** Summary of the decision (v1) */
  summary?: string;
  /** Bullet points explaining the reasoning (v1) */
  reasoningBullets?: string[];
  /** Risk assessment (v1) */
  risk?: RiskAssessment;
}

/**
 * Trade log entry - records a filled trade with explainability fields
 */
export interface TradeLog {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp of trade */
  timestamp: string;
  /** Trade fill data */
  fill: TradeFill;
  /** Reason for the order (from OrderIntent) */
  reason?: string;
  /** Model's probability estimate (0 to 100) */
  modelProb?: number;
  /** Market's implied probability (0 to 100) */
  marketProb?: number;
  /** Calculated edge percentage */
  edgePct?: number;
  /** Stake as percentage of bankroll */
  stakePct?: number;
}

/**
 * Equity entry - records agent equity at a point in time
 */
export interface EquityEntry {
  /** Agent identifier */
  agentId: string;
  /** ISO timestamp */
  timestamp: string;
  /** Equity value (bankroll + unrealized PnL) */
  equity: number;
  /** Bankroll at this point */
  bankroll: number;
  /** Total PnL */
  pnlTotal: number;
}

