import { AgentState, MarketSnapshot, OrderIntent } from '@domain';

/**
 * Common DecisionTrace contract that all strategies must return.
 * This captures the "why" and "how" of a strategy's decision.
 */
export interface DecisionTrace {
  /** Unique agent identifier */
  agentId: string;
  /** ISO timestamp of the decision */
  timestamp: string;
  /** Input state at the time of decision */
  input: {
    state: AgentState;
    marketCount: number;
    eligibleMarketIds?: string[];
  };
  /** Strategy information */
  strategy: {
    name: string;
    version: string;
    parameters: Record<string, unknown>;
  };
  /** The actual decision result */
  decision: {
    /** Whether an order was intended, skipped, or if an error occurred */
    action: 'ORDER' | 'SKIP' | 'ERROR';
    /** High-level reason for the decision */
    reason: string;
    /** Detailed bullet points explaining the logic */
    reasoningBullets: string[];
    /** Whether this was a paper-mode decision */
    isPaperMode: boolean;
    /** Optional metadata for debugging or metrics */
    metadata?: Record<string, unknown>;
  };
  /** Order intents generated by this decision */
  intents: OrderIntent[];
  /** Performance metrics for the decision process */
  performance?: {
    /** Execution time in milliseconds */
    latencyMs: number;
  };
}

/**
 * Input to an agent strategy for decision making
 */
export interface AgentInput {
  /** Current agent state */
  state: AgentState;
  /** Available market snapshots */
  markets: MarketSnapshot[];
}

/**
 * Updated Strategy interface that all agent strategies must implement
 */
export interface IAgentStrategy {
  /** Strategy name */
  readonly name: string;
  /** Strategy version */
  readonly version: string;
   /**
   * Decide on order intents and return a comprehensive trace
   * @param input Agent input containing state and markets
   * @returns A DecisionTrace object (can be a Promise)
   */
  decide(input: AgentInput): DecisionTrace | Promise<DecisionTrace>;
}

